[workspace]
resolver = "2"
members = ["crates/facelock-common", "bin/facelock-daemon"]

[workspace.package]
version = "0.1.0"
edition = "2024"
authors = ["Riju Mondal <rijum8906@gmail.com>"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/rijum8906/rde-facelock"

# Global dependencies to keep versions unified across crates
[workspace.dependencies]
# Internal
facelock-common = { path = "crates/facelock-common" }

thiserror = "2.0"
tokio = { version = "1.40", features = ["full"] }
zbus = { version = "5.19", features = ["tokio"] }

tracing = "0.1.44"
tracing-appender = "0.2.5"
tracing-subscriber = { version = "0.3.23", features=["env-filter"] }
